import "dotenv/config";
import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

const P = (name: string) => `/photos/${name}.jpg`;

async function main() {
  await prisma.property.deleteMany();

  await prisma.property.createMany({
    data: [
      {
        reference: "FL-V-1001",
        offerType: "SALE",
        objectType: "maison",
        objectSubtype: "Maison de maître",
        titleFr: "Maison de maître rénovée, Rive gauche",
        titleEn: "Renovated mansion house, Left Bank",
        descriptionFr:
          "Somptueuse maison de maître entièrement rénovée, nichée dans un parc arboré à Vandoeuvres. Volumes exceptionnels, matériaux nobles, orientation plein sud avec vue dégagée sur la campagne genevoise.",
        descriptionEn:
          "Sumptuous fully renovated mansion set in wooded grounds in Vandoeuvres. Exceptional volumes, fine materials, full-south orientation with open views over the Geneva countryside.",
        street: "Chemin des Princes 12",
        hideStreet: true,
        postalCode: "1253",
        city: "Vandoeuvres",
        district: "Rive gauche",
        canton: "GE",
        rooms: 12,
        bedrooms: 8,
        bathrooms: 5,
        livingArea: 800,
        usableArea: 950,
        volume: 3200,
        yearBuilt: 1902,
        lastRenovation: 2023,
        availability: "by_agreement",
        priceOnRequest: true,
        priceUnit: "total",
        features: ["Piscine", "Vue", "Cheminée", "Garage", "Quartier calme", "Ancienne construction"],
        photos: [P("courtyard_historic"), P("parquet_room"), P("garden_hydrangeas")],
        featured: true,
      },
      {
        reference: "FL-V-1002",
        offerType: "SALE",
        objectType: "appartement",
        objectSubtype: "Attique",
        titleFr: "Attique de standing avec terrasse panoramique",
        titleEn: "Luxury penthouse with panoramic terrace",
        descriptionFr:
          "Au dernier étage d'une résidence de standing à Champel, attique lumineux de 5 pièces avec terrasse de 60 m² offrant une vue imprenable sur le Salève.",
        descriptionEn:
          "On the top floor of a prestigious Champel residence, a light-filled 5-room penthouse with a 60 m² terrace and breathtaking views of the Salève.",
        street: "Avenue de Champel 45",
        postalCode: "1206",
        city: "Genève",
        district: "Champel",
        canton: "GE",
        rooms: 5,
        bedrooms: 3,
        bathrooms: 2,
        floor: 7,
        livingArea: 213,
        yearBuilt: 2011,
        availability: "by_agreement",
        price: 3900000,
        priceUnit: "total",
        features: ["Balcon / Terrasse", "Vue", "Ascenseur", "Garage", "Lave-vaisselle", "Construction Minergie"],
        photos: [P("living_awning"), P("balcony_awning"), P("salon_furnished")],
        featured: true,
      },
      {
        reference: "FL-V-1003",
        offerType: "SALE",
        objectType: "maison",
        objectSubtype: "Villa individuelle",
        titleFr: "Villa contemporaine avec piscine, Cologny",
        titleEn: "Contemporary villa with pool, Cologny",
        descriptionFr:
          "Villa d'architecte de 6.5 pièces sur une parcelle de 1'200 m² à Cologny. Piscine extérieure chauffée, prestations haut de gamme, double garage.",
        descriptionEn:
          "Architect-designed 6.5-room villa on a 1,200 m² plot in Cologny. Heated outdoor pool, high-end finishes, double garage.",
        street: "Chemin de la Gradelle 8",
        hideStreet: true,
        postalCode: "1223",
        city: "Cologny",
        district: "Rive gauche",
        canton: "GE",
        rooms: 6.5,
        bedrooms: 4,
        bathrooms: 3,
        livingArea: 320,
        usableArea: 410,
        yearBuilt: 2018,
        availability: "date",
        availableFrom: new Date("2026-10-01"),
        price: 5200000,
        priceUnit: "total",
        features: ["Piscine", "Garage", "Vue", "Quartier calme", "Nouvelle construction", "Certifié Minergie"],
        photos: [P("villa_jaune"), P("garden_terrace"), P("living_staged")],
        featured: true,
      },
      {
        reference: "FL-L-2001",
        offerType: "RENT",
        objectType: "appartement",
        objectSubtype: "Appartement",
        titleFr: "Appartement traversant avec balcon, Eaux-Vives",
        titleEn: "Dual-aspect apartment with balcony, Eaux-Vives",
        descriptionFr:
          "Bel appartement de 4 pièces traversant au 3e étage, à deux pas du lac et du parc La Grange. Balcon, cuisine équipée, cave.",
        descriptionEn:
          "Beautiful dual-aspect 4-room apartment on the 3rd floor, steps from the lake and La Grange park. Balcony, fitted kitchen, cellar.",
        street: "Rue des Eaux-Vives 78",
        postalCode: "1207",
        city: "Genève",
        district: "Eaux-Vives",
        canton: "GE",
        rooms: 4,
        bedrooms: 2,
        bathrooms: 1,
        floor: 3,
        livingArea: 120,
        yearBuilt: 1965,
        lastRenovation: 2019,
        availability: "date",
        availableFrom: new Date("2026-09-01"),
        price: 3950,
        priceUnit: "month",
        chargesIncluded: true,
        features: ["Balcon / Terrasse", "Ascenseur", "Lave-vaisselle", "Quartier calme"],
        photos: [P("living_staged"), P("bedroom_terrace"), P("garden_terrace")],
        featured: true,
      },
      {
        reference: "FL-L-2002",
        offerType: "RENT",
        objectType: "appartement",
        objectSubtype: "Studio",
        titleFr: "Studio meublé au cœur des Pâquis",
        titleEn: "Furnished studio in the heart of Pâquis",
        descriptionFr:
          "Studio meublé avec goût, idéal pour expatrié. Proche des organisations internationales et de la gare Cornavin. Disponible immédiatement.",
        descriptionEn:
          "Tastefully furnished studio, ideal for expatriates. Close to international organisations and Cornavin station. Available immediately.",
        street: "Rue de Berne 32",
        postalCode: "1201",
        city: "Genève",
        district: "Pâquis",
        canton: "GE",
        rooms: 1.5,
        bedrooms: 1,
        bathrooms: 1,
        floor: 4,
        livingArea: 32,
        availability: "immediately",
        price: 1850,
        priceUnit: "month",
        chargesIncluded: true,
        features: ["Logement meublé", "Ascenseur", "TV câblée"],
        photos: [P("salon_furnished"), P("living_awning")],
      },
      {
        reference: "FL-L-2003",
        offerType: "RENT",
        objectType: "appartement",
        objectSubtype: "Duplex/maisonette",
        titleFr: "Duplex de charme, Vieille-Ville",
        titleEn: "Charming duplex, Old Town",
        descriptionFr:
          "Rare : duplex de 5 pièces dans un immeuble historique de la Vieille-Ville. Poutres apparentes, cheminée d'époque, calme absolu.",
        descriptionEn:
          "Rare: 5-room duplex in a historic Old Town building. Exposed beams, period fireplace, absolute calm.",
        street: "Grand-Rue 15",
        postalCode: "1204",
        city: "Genève",
        district: "Vieille-Ville",
        canton: "GE",
        rooms: 5,
        bedrooms: 3,
        bathrooms: 2,
        floor: 2,
        livingArea: 145,
        ceilingHeight: 3.2,
        yearBuilt: 1780,
        lastRenovation: 2021,
        availability: "by_agreement",
        price: 6075,
        priceUnit: "month",
        chargesIncluded: false,
        features: ["Cheminée", "Quartier calme", "Ancienne construction", "Vue"],
        photos: [P("courtyard_historic"), P("parquet_room"), P("balcony_awning")],
        featured: true,
      },
      {
        reference: "FL-L-2004",
        offerType: "RENT",
        objectType: "maison",
        objectSubtype: "Villa individuelle",
        titleFr: "Villa familiale avec jardin, Onex",
        titleEn: "Family villa with garden, Onex",
        descriptionFr:
          "Villa de 6 pièces avec grand jardin clôturé, idéale pour famille. Proche écoles et transports. Garage double, buanderie privée.",
        descriptionEn:
          "6-room villa with a large fenced garden, ideal for families. Close to schools and transport. Double garage, private laundry.",
        street: "Route de Loëx 11",
        postalCode: "1213",
        city: "Onex",
        canton: "GE",
        rooms: 6,
        bedrooms: 4,
        bathrooms: 2,
        livingArea: 180,
        usableArea: 230,
        yearBuilt: 1988,
        lastRenovation: 2015,
        availability: "date",
        availableFrom: new Date("2026-08-15"),
        price: 5400,
        priceUnit: "month",
        chargesIncluded: false,
        features: ["Garage", "Machine à laver privée", "Convient aux enfants", "Animaux de compagnie autorisés", "Quartier calme"],
        photos: [P("building_modern"), P("garden_terrace"), P("bedroom_terrace")],
      },
      {
        reference: "FL-V-1004",
        offerType: "SALE",
        objectType: "appartement",
        objectSubtype: "Appartement",
        titleFr: "Appartement de standing, quartier des Tranchées",
        titleEn: "High-end apartment, Tranchées district",
        descriptionFr:
          "Dans un immeuble haussmannien, appartement de 5 pièces alliant cachet et confort moderne. Moulures, parquet en point de Hongrie, 3e étage avec ascenseur.",
        descriptionEn:
          "In a Haussmann-style building, a 5-room apartment combining period charm and modern comfort. Mouldings, Hungarian-point parquet, 3rd floor with lift.",
        street: "Rue Charles-Galland 6",
        postalCode: "1206",
        city: "Genève",
        district: "Tranchées",
        canton: "GE",
        rooms: 5,
        bedrooms: 3,
        bathrooms: 2,
        floor: 3,
        livingArea: 168,
        ceilingHeight: 3.1,
        yearBuilt: 1910,
        lastRenovation: 2020,
        availability: "by_agreement",
        price: 2900000,
        priceUnit: "total",
        features: ["Ascenseur", "Cheminée", "Ancienne construction", "Quartier calme"],
        photos: [P("parquet_room"), P("salon_furnished"), P("courtyard_historic")],
      },
    ],
  });

  const count = await prisma.property.count();
  console.log(`Seeded ${count} properties`);
}

main()
  .then(() => prisma.$disconnect())
  .catch((e) => {
    console.error(e);
    prisma.$disconnect();
    process.exit(1);
  });
